[versions]
agp = "8.12.3"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
<<<<<<< HEAD
=======
kotlin = "2.2.0"
coreKtx = "1.17.0"
playServicesAdsApi = "24.6.0"
>>>>>>> 9c8abb4 (ADD PRODUCT PAGE!!!)

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
<<<<<<< HEAD

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
=======
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
play-services-ads-api = { group = "com.google.android.gms", name = "play-services-ads-api", version.ref = "playServicesAdsApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
>>>>>>> 9c8abb4 (ADD PRODUCT PAGE!!!)

